services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - data:/app/data
      - output:/app/output

volumes:
  data:
  output:
