services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - data:/app/data
      - output:/app/output
    command: >
      sh -c "
      if [ \"$RUN_MODE\" = \"train\" ]; then
        python -m train;
      else
        python -m main;
      fi
      "

volumes:
  data:
  output: