services:
  train:
    build:
      context: .
      dockerfile: src/ml/Dockerfile
    env_file: .env
    volumes:
      - ./data:/app/data
    profiles:
      - train
    restart: "no"

  app:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./output:/app/output
    profiles:
      - app
    restart: "no"
